// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1LFWb1KzRGwlatagRxJANKTG0TmVis2A',
    appId: '1:54327740125:web:562bae7791059ae00cbd34',
    messagingSenderId: '54327740125',
    projectId: 'fir-demo-02-4542e',
    authDomain: 'fir-demo-02-4542e.firebaseapp.com',
    storageBucket: 'fir-demo-02-4542e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWncoTslJvbjLteeLNSdsJJqI_hdWmMTU',
    appId: '1:54327740125:android:e990f3bbde5d80f00cbd34',
    messagingSenderId: '54327740125',
    projectId: 'fir-demo-02-4542e',
    storageBucket: 'fir-demo-02-4542e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOwt2fKWUbGb8yrhij2nokvSWFrilMyTc',
    appId: '1:54327740125:ios:27993e3b8f5392100cbd34',
    messagingSenderId: '54327740125',
    projectId: 'fir-demo-02-4542e',
    storageBucket: 'fir-demo-02-4542e.firebasestorage.app',
    iosBundleId: 'com.example.firebase01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOwt2fKWUbGb8yrhij2nokvSWFrilMyTc',
    appId: '1:54327740125:ios:27993e3b8f5392100cbd34',
    messagingSenderId: '54327740125',
    projectId: 'fir-demo-02-4542e',
    storageBucket: 'fir-demo-02-4542e.firebasestorage.app',
    iosBundleId: 'com.example.firebase01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1LFWb1KzRGwlatagRxJANKTG0TmVis2A',
    appId: '1:54327740125:web:a4d0fdaadd85f27b0cbd34',
    messagingSenderId: '54327740125',
    projectId: 'fir-demo-02-4542e',
    authDomain: 'fir-demo-02-4542e.firebaseapp.com',
    storageBucket: 'fir-demo-02-4542e.firebasestorage.app',
  );
}
