name: flutter_provider_redux_01

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  redux_thunk: ^0.4.0
  http: ^1.3.0
  shared_preferences: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  