name: app_responsive_ver_b
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  googleapis: ^13.2.0
  http: ^1.2.2
  provider: ^6.1.2
  url_launcher: ^6.3.1
  flex_color_scheme: ^8.1.0
  go_router: ^14.6.3
  split_view: ^3.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

