// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb2XqcrQ9JpImtqST3jZwFt_j646mNZLA',
    appId: '1:958711537121:web:412ceb401f80a3d85346a0',
    messagingSenderId: '958711537121',
    projectId: 'flutter-demo-a5ff8',
    authDomain: 'flutter-demo-a5ff8.firebaseapp.com',
    storageBucket: 'flutter-demo-a5ff8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgv2MN7PRIc0msmPTBLd-wyUx4XKcLNJI',
    appId: '1:958711537121:android:06fc523531ad1cab5346a0',
    messagingSenderId: '958711537121',
    projectId: 'flutter-demo-a5ff8',
    storageBucket: 'flutter-demo-a5ff8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP_v7h3Bo_1jorG5SaXurauDEPA8WcudE',
    appId: '1:958711537121:ios:9adb7cdcd9f6d9955346a0',
    messagingSenderId: '958711537121',
    projectId: 'flutter-demo-a5ff8',
    storageBucket: 'flutter-demo-a5ff8.firebasestorage.app',
    iosBundleId: 'com.example.firebase01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP_v7h3Bo_1jorG5SaXurauDEPA8WcudE',
    appId: '1:958711537121:ios:9adb7cdcd9f6d9955346a0',
    messagingSenderId: '958711537121',
    projectId: 'flutter-demo-a5ff8',
    storageBucket: 'flutter-demo-a5ff8.firebasestorage.app',
    iosBundleId: 'com.example.firebase01',
  );
}
